### ISSUE TITLE
[Bug] CI/CD Missing credentials in config, Deployment Error

### ISSUE THREAD

**Issue by srpiatt** [awslabs/service-workbench-on-aws#1060]
**Describe the bug**
We have been encountering a missing credentials error during deployment from the ci/cd pipeline.

**To Reproduce**
1. Create a new CI/CD pipeline using `./scripts/cicd-deploy.sh` with SWB version 5.0.0 or 4.3.2.

**Expected behavior**
CI/CD Pipeline is able to deploy without encountering a Missing credentials error.

**Versions (please complete the following information):**
 - Release Version installed 4.3.2 & 5.0.0

**Additional context**
I updated our forked github repo to revert some changes in one of our accounts, and the existing pipeline worked-- successfully building the reverted code. Then, I updated the pipeline stack by running the `cicd-deploy.sh` script- to update the github key- and the pipeline failed to deploy, returning this missing credentials error. The only difference between success and failure, with the same code, was that the pipeline stack update. (This was with SWB version 4.3.2.)

I then tried to create a new pipeline stack in a different account, using a newer SWB version 5.0.0, and it also failed. (I have not yet tried the most recent SWB version.)

- Has anyone else encountered an issue like this on new pipeline deployments?
- Are there any changes that happened to CodeBuild recently that no longer exposes credentials in new pipeline stacks?
- Or, has there been a significant change to ci/cd pipeline script or SDKs in newer SWB versions that we need to pull in order to get this to work?

----
```
Credentials Error --------------------------------------
--
876 |  
877 | CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
878 | at Object.openSync (fs.js:457:3)
879 | at Object.readFileSync (fs.js:359:35)
880 | at Object.readFileSync (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/util.js:95:26)
881 | at IniLoader.parseFile (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:6:47)
882 | at IniLoader.loadFrom (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
883 | at Object.getProfilesFromSharedConfig (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/util.js:976:41)
884 | at SharedIniFileCredentials.load (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:98:31)
885 | at SharedIniFileCredentials.coalesceRefresh (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/credentials.js:205:12)
886 | at SharedIniFileCredentials.refresh (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:170:10)
887 | at SharedIniFileCredentials.get (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/credentials.js:122:12)
888 | at getAsyncCredentials (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/config.js:398:24)
889 | at Config.getCredentials (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/config.js:418:9)
890 | at Request.VALIDATE_CREDENTIALS (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/event_listeners.js:81:26)
891 | at Request.callListeners (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
892 | at Request.emit (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
893 | at Request.emit (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/request.js:686:14)
894 | at Request.transition (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/request.js:22:10)
895 | at AcceptorStateMachine.runTo (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/state_machine.js:14:12)
896 | at Request.runTo (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/request.js:406:15)
897 | at /codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/request.js:795:12
898 | at new Promise (<anonymous>)
899 | at Request.promise (/codebuild/local-cache/custom/dba27c31aad935787bb275c3e5e4e957708f15386de599eff1db476022cd7e4c/node_modules/.pnpm/aws-sdk@2.1015.0/node_modules/aws-sdk/lib/request.js:781:12)
900 | at getAwsAccountInfo (/codebuild/output/src802652068/src/addons/addon-base/packages/serverless-settings-helper/lib/aws-acc-context.js:28:56)
901 | at Object.merged (/codebuild/output/src802652068/src/addons/addon-base/packages/serverless-settings-helper/lib/index.js:173:46)
902 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
903 |  
904 | For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
905 |  
906 | Get Support --------------------------------------------
907 | Docs:          docs.serverless.com
908 | Bugs:          github.com/serverless/serverless/issues
909 | Issues:        forum.serverless.com
910 |  
911 | Your Environment Information ---------------------------
912 | Operating System:          linux
913 | Node Version:              12.16.1
914 | Framework Version:         1.67.3
915 | Plugin Version:            3.6.6
916 | SDK Version:               2.3.0
917 | Components Version:        2.29.0
```

**Comment by SanketD92** [comment]
Since CI/CD picks up the stage file from `/main/config/settings/<stage>.yml` file for deployment, you need to comment/remove the `awsProfile` line from `main/cicd/cicd-pipeline/config/settings/<stage>.yml` file to avoid credentials clashes in serverless.

**Comment by SanketD92** [comment]
Since CI/CD picks up the stage file from `/main/config/settings/<stage>.yml` for deployment, you need to remove the `awsProfile` line from `main/cicd/cicd-pipeline/config/settings/<stage>.yml` file to avoid credentials clashes in serverless.

**Comment by srpiatt** [comment]
I tried your suggestion two ways.

1. When I leave the `awsProfile` parameter in `/main/config/settings/<stage>.yml` and remove it from `main/cicd/cicd-pipeline/config/settings/<stage>.yml` it still returns the same credential error in the pipeline build step, after the ci/cd pipeline stack is updated.

2. When I remove the `awsProfile` parameter from both stage files, serverless fails to deploy the new ci/cd pipeline stack and returns this error locally:
```
Serverless Warning --------------------------------------

  A valid service attribute to satisfy the declaration 'self:provider.profile' could not be found.


  Serverless Error ---------------------------------------

  Trying to populate non string value into a string for variable ${self:provider.profile}. Please make sure the value of the property is a string.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.20.1
     Framework Version:         1.67.3
     Plugin Version:            3.6.6
     SDK Version:               2.3.0
     Components Version:        2.29.0
```

**Comment by SanketD92** [comment]
There seems to be some bad linking leftover from previous attempts. Could you try running `./scripts install.sh <stage>` before deploying the CI/CD stack?

If that doesn't work either:

1. Delete the CICD stack from CloudFormation (and associated bucket in S3)
2. Run `./scripts/install.sh <stage>` to install all dependencies and link packages
3. Deploy the CI/CD package (with `awsProfile` only declared in `/main/config/settings/<stage>.yml`)

**Comment by SanketD92** [comment]
Apologies, I made a copy paste error in my previous message. 

You need to delete the `awsProfile` line from `/main/config/settings/<stage>.yml` and keep it in `/main/cicd/cicd-pipeline/config/settings/<stage>.yml` when you're deploying the CICD stack. I'd also recommend running `./scripts/install.sh <stage>` beforehand.

Let us know if this doesn't work. We might then need to look into your serverless, node, and pnpm versions.

**Comment by srpiatt** [comment]
I see-- I should have tried that. It works this way. So the cause is a serverless credential clash with the two stage files. I'll make note of this issue internally.
