### ISSUE TITLE
[Bug] PreSignUp invocation failed due to error AccessDeniedException.

### ISSUE THREAD

**Issue by BoPeng** [awslabs/service-workbench-on-aws#1136]
**Describe the bug**
Refresh installation (in `prod` mode) failed due to `AccessDeniedException` during the creation of a user pool, maybe due to the existence of another `userPool` created in `dev` mode.

**To Reproduce**

This installation happens on a Cloud9 EC2 instance that was used to install a dev installation, 
1. `git update` the repository, 
2. made a copy of `example.yml` to `prod.yml`, 
3. change `envType` in `prod.yml` from `dev` to `prod`
4. Run `sh scripts/environment-deploy.sh prod`

**Expected behavior**
Installation should succeed.

**Screenshots**

![image](https://user-images.githubusercontent.com/9889312/222931886-312d7f3d-59b6-4bf0-9e4f-b13595276d2f.png)

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3], git master and v5.2.7
 - Is the deployment from a forked version of the repository? ok

**Additional context**
Change the email address to a valid email address lead to the same error message.

**Comment by BoPeng** [comment]
https://stackoverflow.com/questions/42460846/when-i-try-to-login-using-aws-cognito-i-get-an-accessdeniedexception-about-my-cu looks related.

**Comment by BoPeng** [comment]
I tried to explore this error:

1. `Lambda -> Functions -> oh-sw-postDeployment-prod-postDeployment` , which shows the lambda function fails.
2. `Cloud Watch` for the event, 
```json
2023-03-09T06:01:17.235Z	baf4d899-35dd-4245-b897-b89a8a101dc1	INFO	{
    "message": "PreSignUp invocation failed due to error AccessDeniedException.",
    "code": "UnexpectedLambdaException",
    "time": "2023-03-09T06:01:17.234Z",
    "requestId": "a94e5a73-8f12-4255-848f-019de8e3e149",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 350.1692156117091
}
```

```json
2023-03-09T06:01:17.236Z	baf4d899-35dd-4245-b897-b89a8a101dc1	ERROR	Invoke Error 	{
    "errorType": "UnexpectedLambdaException",
    "errorMessage": "PreSignUp invocation failed due to error AccessDeniedException.",
    "code": "UnexpectedLambdaException",
    "message": "PreSignUp invocation failed due to error AccessDeniedException.",
    "time": "2023-03-09T06:01:17.234Z",
    "requestId": "a94e5a73-8f12-4255-848f-019de8e3e149",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 350.1692156117091,
    "stack": [
        "UnexpectedLambdaException: PreSignUp invocation failed due to error AccessDeniedException.",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}
```

3. This lambda function has role [prod-oh-sw-postDeployment-RolePostDeploymentLambda](https://us-east-2.console.aws.amazon.com/iam/home#/roles/prod-oh-sw-postDeployment-RolePostDeploymentLambda?section=permissions)
4. The role has a permission [AmazonCognitoPowerUser](https://us-east-1.console.aws.amazon.com/iam/home#/policies/arn:aws:iam::aws:policy/AmazonCognitoPowerUser), 

```jaon
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "cognito-identity:*",
                "cognito-idp:*",
                "cognito-sync:*",
                "iam:ListRoles",
                "iam:ListOpenIdConnectProviders",
                "iam:GetRole",
                "iam:ListSAMLProviders",
                "iam:GetSAMLProvider",
                "kinesis:ListStreams",
                "lambda:GetPolicy",
                "lambda:ListFunctions",
                "sns:GetSMSSandboxAccountStatus",
                "sns:ListPlatformApplications",
                "ses:ListIdentities",
                "ses:GetIdentityVerificationAttributes",
                "mobiletargeting:GetApps",
                "acm:ListCertificates"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "iam:AWSServiceName": [
                        "cognito-idp.amazonaws.com",
                        "email.cognito-idp.amazonaws.com"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "iam:DeleteServiceLinkedRole",
                "iam:GetServiceLinkedRoleDeletionStatus"
            ],
            "Resource": [
                "arn:aws:iam::*:role/aws-service-role/cognito-idp.amazonaws.com/AWSServiceRoleForAmazonCognitoIdp*",
                "arn:aws:iam::*:role/aws-service-role/email.cognito-idp.amazonaws.com/AWSServiceRoleForAmazonCognitoIdpEmail*"
            ]
        }
    ]
}
```

The permission contains action `"cognito-idp:*"` so I am not sure what the problem was.

**Comment by BoPeng** [comment]
ok, after a lot of exploration effort, I noticed that the `lambda-access` policy for IAM role `dev-va-sw-postDeployment-RolePostDeploymentLambda`  has a resource that points to lambda functions from a different region. This might not be the reason for this particular error but does remind me of the fact that these resources are not updated when we install service workbench on different regions, with different settings etc.

I therefore removed all lambda functions, IAM roles and policies, s3 buckets etc and restarted the installation from scratch, and I no longer see this error.
